### ISSUE TITLE
FizzBuzzer Class and execute method should not exist yet

### ISSUE THREAD

**Issue by spilth** [tim-butterworth/tdd-katas#1]
I'm not sure what state of the code the repo is meant to represent but I would argue that the class `FizzBuzzer` and it's method `execute` shouldn't even exist until you have a test trying to use that class and method that won't compile because they don't exist yet. This helps the test express the type of API you want (what's the class called, what's the method called, what type do I send it, what should it return)

**Comment by tim-butterworth** [comment]
Brian! How is it going? I could make that change, I am trying to get a set of intro type level katas going, if you know of some good ones I would love to add them to this repo.
